{
 "title": "AIRq Main monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "metric_name",
    "query": "aqi,voc,pm1,pm2,pm10,temperature,humidity,pressure"
   },
   { "name": "interval", "query": "3h,1d,2d,3d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Historical view of $metric_name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"airq\")\n|> range(start: -${interval})\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/${metric_name}\"\n)"
      }
     ]
    },
    {
     "title": "Spikes history of $metric_name",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"airq\")\n|> range(start: -${interval})\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/$metric_name\"\n)"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"airq\")\n|> range(start: -10h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/voc\"\n)\n|> mean()"
      }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -10d)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/aqi\"\n)\n|> last()"
    }
   ]
  },
  {
   "title": "AQI",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/aqi\"\n)"
    }
   ]
  },
  {
   "title": "AQI Spikes",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/aqi\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm1\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/humidity\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm2\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pressure\"\n)"
    }
   ]
  },
  {
   "title": "AQI distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/aqi\"\n)"
    }
   ]
  },
  {
   "title": "Spike detection",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm1\"\n)"
    },
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm2\"\n)"
    },
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm10\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm10\"\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -5m)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/temperature\"\n)"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -10d)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/voc\"\n)\n|> last()"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/voc\"\n)"
    }
   ]
  },
  {
   "title": "PM History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm1\"\n)"
    },
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm2\"\n)"
    },
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/pm10\"\n)"
    }
   ]
  },
  {
   "title": "VOC Distribution",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/voc\"\n)"
    }
   ]
  },
  {
   "title": "VOC Spikes",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"airq\")\n|> range(start: -1h)\n|> filter(fn: (r) =>\n      r.topic == \"/airq/dust/voc\"\n)"
    }
   ]
  }
 ]
}